# Site settings
title: 绿野蓝杉的主页
description: 一个技术爱好者的个人空间
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: 绿 野 蓝 杉
user_description: 一个热爱技术和音乐的视频博主
user_title: 音乐•编程•动漫
email: lvyelanshan@gmail.com
twitter_username: lvyelanshan
github_username:  Jacky-lei1
gplus_username:  lvyelanshan


#Valine评论模块
valine:
  enable: true
  src: //unpkg.com/valine/dist/Valine.min.js
  appId: r7waXQyvsCs1E7Q2a0JQqB8f-gzGzoHsz
  appKey: HWF8pxlPAz7YlJ7vU7J8oPDk
  notify: true # 评论回复邮件提醒
  verify: true # 验证码服务
  avatar: retro
  placeholder: 留下您的足迹！
  highlight: true # 代码高亮
  avatarForce: false # 每次访问强制拉取最新的评论列表头像
  recordIP: true # 记录评论者IP
  pageSize: 10 #分页，每页显示10条


# Google-analytics
google-analytics:
  id: "UA-154317930-1"

exclude: ['package.json', 'src' , 'node_modules']
